### ISSUE TITLE
TODO for initial "release"

### ISSUE THREAD

**Issue by MarshallOfSound** [GPMDP/google-play-music-desktop-remote#3]
@mmazzarolo Feel free to add whatever you want here

* [ ] A lot of tests, this is React based so we should be able to do this with https://github.com/glenjamin/skin-deep
* [ ] ZeroConf
    * [ ] Auto discover GPMDP api's on the local network
    * [ ] Display a list of all found GPMDP
    * [ ] Allow a user to manually input an IP address aswell
* [ ] Allow the user to view and play items in there queue **blocked** [PR](https://github.com/gmusic-utils/gmusic.js/pull/38)
    * [ ] Have a queue UI
    * [ ] Tapping a song plays that song
    * [ ] Allow the user to clear the queue
    * [ ] Allow the user to start the "I'm feeling lucky playlist"

**Comment by mmazzarolo** [comment]
Adding unit tests is on top of my list.  
For testing UI components in React-Native Enzyme and Jest are the most common and documented options.
